package com.dragn0007.dragnpets.entities.cat;

import com.dragn0007.dragnlivestock.LivestockOverhaul;
import com.dragn0007.dragnpets.PetsOverhaul;
import net.minecraft.resources.ResourceLocation;

public enum CatMarkingOverlay {
        NONE(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/none.png")),
        BLACK_COLORPOINT(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/black_colorpoint.png")),
        BLACK_MITTENS(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/black_mittens.png")),
        BLACK_SPLOTCHED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/black_splotched.png")),
        BLACK_SPOTTED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/black_spotted.png")),
        BLACK_STRIPE(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/black_stripe.png")),
        BLACK_STRIPED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/black_striped.png")),
        BLACK_TABBY(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/black_tabby.png")),
        BLUE_COLORPOINT(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/blue_colorpoint.png")),
        BLUE_MITTENS(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/blue_mittens.png")),
        BLUE_SPLOTCHED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/blue_splotched.png")),
        BLUE_SPOTTED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/blue_spotted.png")),
        BLUE_STRIPE(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/blue_stripe.png")),
        BLUE_STRIPED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/blue_striped.png")),
        BLUE_TABBY(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/blue_tabby.png")),
        BROWN_COLORPOINT(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/brown_colorpoint.png")),
        BROWN_MITTENS(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/brown_mittens.png")),
        BROWN_SPLOTCHED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/brown_splotched.png")),
        BROWN_SPOTTED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/brown_spotted.png")),
        BROWN_STRIPE(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/brown_stripe.png")),
        BROWN_STRIPED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/brown_striped.png")),
        BROWN_TABBY(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/brown_tabby.png")),
        CHOCOLATE_COLORPOINT(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/chocolate_colorpoint.png")),
        CHOCOLATE_MITTENS(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/chocolate_mittens.png")),
        CHOCOLATE_SPLOTCHED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/chocolate_splotched.png")),
        CHOCOLATE_SPOTTED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/chocolate_spotted.png")),
        CHOCOLATE_STRIPE(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/chocolate_stripe.png")),
        CHOCOLATE_STRIPED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/chocolate_striped.png")),
        CHOCOLATE_TABBY(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/chocolate_tabby.png")),
        CREAM_MITTENS(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/cream_mittens.png")),
        CREAM_SPLOTCHED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/cream_splotched.png")),
        CREAM_SPOTTED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/cream_spotted.png")),
        CREAM_STRIPE(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/cream_stripe.png")),
        CREAM_STRIPED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/cream_striped.png")),
        CREAM_TABBY(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/cream_tabby.png")),
        LILAC_COLORPOINT(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/lilac_colorpoint.png")),
        LILAC_MITTENS(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/lilac_mittens.png")),
        LILAC_SPLOTCHED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/lilac_splotched.png")),
        LILAC_SPOTTED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/lilac_spotted.png")),
        LILAC_STRIPE(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/lilac_stripe.png")),
        LILAC_STRIPED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/lilac_striped.png")),
        LILAC_TABBY(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/lilac_tabby.png")),
        MAHOGANY_COLORPOINT(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/mahogany_colorpoint.png")),
        MAHOGANY_MITTENS(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/mahogany_mittens.png")),
        MAHOGANY_SPLOTCHED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/mahogany_splotched.png")),
        MAHOGANY_SPOTTED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/mahogany_spotted.png")),
        MAHOGANY_STRIPE(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/mahogany_stripe.png")),
        MAHOGANY_STRIPED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/mahogany_striped.png")),
        MAHOGANY_TABBY(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/mahogany_tabby.png")),
        RED_COLORPOINT(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/red_colorpoint.png")),
        RED_MITTENS(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/red_mittens.png")),
        RED_SPLOTCHED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/red_splotched.png")),
        RED_SPOTTED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/red_spotted.png")),
        RED_STRIPE(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/red_stripe.png")),
        RED_STRIPED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/red_striped.png")),
        RED_TABBY(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/red_tabby.png")),
        SEAL_COLORPOINT(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/seal_colorpoint.png")),
        SEAL_MITTENS(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/seal_mittens.png")),
        SEAL_SPLOTCHED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/seal_splotched.png")),
        SEAL_SPOTTED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/seal_spotted.png")),
        SEAL_STRIPE(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/seal_stripe.png")),
        SEAL_STRIPED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/seal_striped.png")),
        SEAL_TABBY(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/seal_tabby.png")),
        SILVER_COLORPOINT(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/silver_colorpoint.png")),
        SILVER_MITTENS(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/silver_mittens.png")),
        SILVER_SPLOTCHED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/silver_splotched.png")),
        SILVER_SPOTTED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/silver_spotted.png")),
        SILVER_STRIPE(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/silver_stripe.png")),
        SILVER_STRIPED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/silver_striped.png")),
        SILVER_TABBY(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/silver_tabby.png")),
        TAN_COLORPOINT(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/tan_colorpoint.png")),
        TAN_MITTENS(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/tan_mittens.png")),
        TAN_SPLOTCHED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/tan_splotched.png")),
        TAN_SPOTTED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/tan_spotted.png")),
        TAN_STRIPE(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/tan_stripe.png")),
        TAN_STRIPED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/tan_striped.png")),
        TAN_TABBY(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/tan_tabby.png")),
        WHITE_COLORPOINT(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/white_colorpoint.png")),
        WHITE_MITTENS(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/white_mittens.png")),
        WHITE_SPLOTCHED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/white_splotched.png")),
        WHITE_SPOTTED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/white_spotted.png")),
        WHITE_STRIPE(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/white_stripe.png")),
        WHITE_STRIPED(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/white_striped.png")),
        WHITE_TABBY(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/white_tabby.png")),
        PURE_WHITE(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/pure_white.png")),
        CALICO(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/calico.png")),
        TUXEDO(new ResourceLocation(PetsOverhaul.MODID, "textures/entity/cat/overlay/tuxedo.png")),
        ;

        public final ResourceLocation resourceLocation;
        CatMarkingOverlay(ResourceLocation resourceLocation) {
                this.resourceLocation = resourceLocation;
        }

        public static CatMarkingOverlay overlayFromOrdinal(int overlay) { return CatMarkingOverlay.values()[overlay % CatMarkingOverlay.values().length];
        }
}
